# Suskind_Router settings. You can learn more about this file on the Sukind Framework's wiki:
# http://code.google.com/p/suskind/wiki/Reference_Routing

# default rules, please do not remove them.
files:
  url: /assets/*
  param: { module: Suskind_Loader, action: getFile}

homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

# Süskind's special routes.
about:
  url: /about
  param: { module: Suskind, action: about}

info:
  url: /info
  param: { module: Suskind, action: info}