# Suskind_Request directives. You can learn more about this file on the Sukind Framework's wiki:
# http://code.google.com/p/suskind/wiki/Reference_Request

default:
  is_secure: false
  # Restricted IP addresses:
  # restricted: [127.0.1.1]